apiVersion: apps/v1
kind: Deployment
metadata:
  name: metric-simulator
  namespace: default
  labels:
    app: metric-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metric-simulator
  template:
    metadata:
      labels:
        app: metric-simulator
    spec:
      containers:
      - name: metric-simulator
        image: metric-simulator:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
